// This file is auto-generated to stream tracks from remote URLs.
// Storing URLs instead of raw bytes keeps the binary size small.

pub static RADIO_TRACKS: &[(&str, &str)] = &[
    ("Go Cart (Loop Mix)", "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Go%20Cart.mp3"),
    ("Laser Groove", "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Laser%20Groove.mp3"),
    ("Retro Future Clean", "https://incompetech.com/music/royalty-free/mp3-royaltyfree/RetroFuture%20Clean.mp3"),
    ("Retro Future Dirty", "https://incompetech.com/music/royalty-free/mp3-royaltyfree/RetroFuture%20Dirty.mp3"),
    ("Funk Game Loop", "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Funk%20Game%20Loop.mp3"),
    ("Space Fighter Loop", "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Space%20Fighter%20Loop.mp3"),
    ("Loopster", "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Loopster.mp3"),
    ("Rocket Power", "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Rocket%20Power.mp3"),
    ("Son Of A Rocket", "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Son%20Of%20A%20Rocket.mp3"),
    ("Happy Happy Game Show", "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Happy%20Happy%20Game%20Show.mp3"),
    ("Sergio's Magic Dustbin", "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Sergio%27s%20Magic%20Dustbin.mp3"),
    ("Mesmerizing Galaxy", "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Mesmerizing%20Galaxy%20Loop.mp3"),
    ("Galactic Rap", "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Galactic%20Rap.mp3"),
    ("Cloud Dancer", "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Cloud%20Dancer.mp3"),
    ("Brain Dance", "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Brain%20Dance.mp3"),
    ("Southern Gothic", "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Southern%20Gothic.mp3"),
    ("I Got a Stick Arr Bryan Teoh", "https://incompetech.com/music/royalty-free/mp3-royaltyfree/I%20Got%20a%20Stick%20Arr%20Bryan%20Teoh.mp3"),
    ("I Got a Stick Feat James Gavins", "https://incompetech.com/music/royalty-free/mp3-royaltyfree/I%20Got%20a%20Stick%20Feat%20James%20Gavins.mp3"),
    ("Boogie Party", "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Boogie%20Party.mp3"),
    ("Journey To Ascend", "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Journey%20To%20Ascend.mp3"),
    ("Fox Tale Waltz Part 1", "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Fox%20Tale%20Waltz%20Part%201.mp3"),
    ("Grand Dark Waltz Trio Vivace", "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Grand%20Dark%20Waltz%20Trio%20Vivace.mp3"),
    ("Grand Dark Waltz Trio Allegro", "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Grand%20Dark%20Waltz%20Trio%20Allegro.mp3"),
    ("Fox Tale Waltz Part 1 Instrumental", "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Fox%20Tale%20Waltz%20Part%201%20Instrumental.mp3"),
    ("Starting Out Waltz Vivace", "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Starting%20Out%20Waltz%20Vivace.mp3"),
    ("Starting Out Waltz Allegretto", "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Starting%20Out%20Waltz%20Allegretto.mp3"),
    ("Grand Dark Waltz Allegro", "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Grand%20Dark%20Waltz%20Allegro.mp3"),
    ("Feral Angel Waltz", "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Feral%20Angel%20Waltz%20.mp3"),
    ("Burn The World Waltz", "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Burn%20The%20World%20Waltz%20.mp3"),
    ("Ancient Mystery Waltz (Presto)", "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Ancient%20Mystery%20Waltz%20Presto.mp3"),
    ("Ancient Mystery Waltz (Vivace)", "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Ancient%20Mystery%20Waltz%20Vivace.mp3"),
    ("Pleasant Porridge", "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Pleasant%20Porridge.mp3"),
    ("Ethernight Club", "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Ethernight%20Club.mp3"),
    ("Voxel Revolution", "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Voxel%20Revolution.mp3"),
    ("Neon Laser Horizon", "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Neon%20Laser%20Horizon.mp3"),
    ("On Hold for You", "https://incompetech.com/music/royalty-free/mp3-royaltyfree/On%20Hold%20for%20You.mp3"),
    ("Canon In D For 8 Bit Synths", "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Canon%20In%20D%20For%208%20Bit%20Synths.mp3"),
    ("SCP-x7x (6th Floor)", "https://incompetech.com/music/royalty-free/mp3-royaltyfree/SCP-x7x.mp3"),
    ("SCP-x5x (Outer Thoughts)", "https://incompetech.com/music/royalty-free/mp3-royaltyfree/SCP-x5x.mp3"),
    ("Moonlight Beach", "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Moonlight%20Beach.mp3"),
    ("The Entertainer", "https://incompetech.com/music/royalty-free/mp3-royaltyfree/The%20Entertainer.mp3"),
    ("Maple Leaf Rag", "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Maple%20Leaf%20Rag.mp3"),
    ("Frogs Legs Rag", "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Frogs%20Legs%20Rag.mp3"),
    ("Screen Saver", "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Screen%20Saver.mp3"),
    ("Hillbilly Swing", "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Hillbilly%20Swing.mp3"),
    ("Del Rio Bravo", "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Del%20Rio%20Bravo.mp3"),
    ("Krampus Workshop", "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Krampus%20Workshop.mp3"),
    ("Dance of the Tuba Plum Fairy", "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Dance%20of%20the%20Tuba%20Plum%20Fairy.mp3"),
];

pub static WALK_TRACKS: &[(&str, &str)] = &[
    ("Bassa Island Game Loop", "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Bassa%20Island%20Game%20Loop.mp3"),
    ("Townie Loop", "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Townie%20Loop.mp3"),
    ("Sauropod Spotting", "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Sauropod%20Spotting.mp3"),
    ("Cretaceous Dawn", "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Cretaceous%20Dawn.mp3"),
    ("That Zen Moment", "https://incompetech.com/music/royalty-free/mp3-royaltyfree/That%20Zen%20Moment.mp3"),
    ("Lord of the Rangs", "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Lord%20of%20the%20Rangs.mp3"),
    ("Equatorial Complex", "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Equatorial%20Complex.mp3"),
    ("Vibing Over Venus", "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Vibing%20Over%20Venus.mp3"),
];

pub static WANTED_TRACKS: &[(&str, &str)] = &[
    ("Zombie Chase", "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Zombie%20Chase.mp3"),
    ("Chase Pulse", "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Chase%20Pulse.mp3"),
    ("Dentaneosuchus Hunt", "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Dentaneosuchus%20Hunt.mp3"),
    ("Adventures in Adventureland", "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Adventures%20in%20Adventureland.mp3"),
    ("Trouble with Tribals", "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Trouble%20with%20Tribals.mp3"),
    ("Le Grand Chase", "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Le%20Grand%20Chase.mp3"),
    ("Hot Pursuit", "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Hot%20Pursuit.mp3"),
    ("Outfoxing the Fox", "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Outfoxing%20the%20Fox.mp3"),
];
